name: ci

on:
  pull_request: {}  # run on ANY PR for ANY branch

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    env:
      CI: true
      NEXT_TELEMETRY_DISABLED: 1
      HUSKY: 0   # skip local git hooks in CI

    steps:
      - uses: actions/checkout@v5

      # Install pnpm (per doc)
      - uses: pnpm/action-setup@v2
        with:
          version: 9

      # Setup Node (per doc). Reads version from .nvmrc.
      # Also enables pnpm cache as recommended.
      - uses: actions/setup-node@v5
        with:
          node-version: '20.17.0'
          cache: 'pnpm'

      # Per doc: use --frozen-lockfile on CI for PNPM
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: pnpm test